ALTER TABLE incidents
    ADD COLUMN IF NOT EXISTS predicted_category VARCHAR(50),
    ADD COLUMN IF NOT EXISTS predicted_severity VARCHAR(20),
    ADD COLUMN IF NOT EXISTS category_confidence DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS severity_confidence DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS triage_route VARCHAR(50),
    ADD COLUMN IF NOT EXISTS model_tier VARCHAR(20),
    ADD COLUMN IF NOT EXISTS human_review_required BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS triage_reason TEXT,
    ADD COLUMN IF NOT EXISTS triaged_at TIMESTAMPTZ;